### ISSUE TITLE
1.3.3 don't build on mac

### ISSUE THREAD

**Issue by yihuang** [bugsnag/panicwrap#22]
The `+build` filter logic on `dup2.go` should be:
```
not windows and not (linux and arm64)
```
But current meaning seems to be:
```
not windows and linux and (not arm64)
```

Maybe change it to:
```
// +build !windows
// +build !linux !arm64
```

**Comment by abigailbramble** [comment]
Fixed in [v1.3.4](https://github.com/bugsnag/panicwrap/releases/tag/v1.3.4)
